// <auto-generated />
using System;
using Corona.Persistence.EFCore.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Corona.Api.Persistence.EFCore.Migrations
{
    [DbContext(typeof(CoronaDbContext))]
    [Migration("20200317210353_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Corona.Api.Domain.Entities.Report", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("Corona.Api.Domain.Entities.Report", b =>
                {
                    b.OwnsMany("Corona.Api.Domain.Entities.Record", "Records", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<float>("Latitude")
                                .HasColumnType("real");

                            b1.Property<float>("Longitude")
                                .HasColumnType("real");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ReportId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("Id");

                            b1.HasIndex("ReportId");

                            b1.ToTable("Record");

                            b1.WithOwner()
                                .HasForeignKey("ReportId");

                            b1.OwnsMany("Corona.Api.Domain.Entities.Data", "Data", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Confirmed")
                                        .HasColumnType("int");

                                    b2.Property<DateTime>("Date")
                                        .HasColumnType("datetime2");

                                    b2.Property<int>("Deaths")
                                        .HasColumnType("int");

                                    b2.Property<Guid>("RecordId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Recovered")
                                        .HasColumnType("int");

                                    b2.HasKey("Id");

                                    b2.HasIndex("RecordId");

                                    b2.ToTable("Data");

                                    b2.WithOwner()
                                        .HasForeignKey("RecordId");
                                });
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
